TASKS = [
    {
        "task_id": "booking_standard_post_op",
        "task_family": "booking",
        "patient_message": (
            "Hi, I need to start home physiotherapy after knee surgery. Tomorrow evening works, "
            "and my apartment is accessible."
        ),
        "patient_history_summary": "Post-op knee replacement discharge 5 days ago. No red-flag symptoms reported.",
        "care_plan_summary": "New referral for home physio assessment and mobility support, 2 visits per week.",
        "visit_context": {
            "location": "Andheri West",
            "preferred_window": "tomorrow evening",
            "scheduled_visit": None,
            "caregiver_required": False,
            "home_access": "lift available",
        },
        "appointment_context": {
            "existing_visit": None,
            "therapist_availability": "tomorrow 6 PM confirmed",
            "serviceability_notes": "standard service area",
        },
        "hidden_state": {
            "true_clinical_severity": "low",
            "home_visit_suitability": "suitable",
            "latent_adherence_risk": "low",
            "escalation_necessity": "none",
            "serviceability_status": "serviceable",
        },
        "operational_constraints": [
            "Serviceable pincode confirmed.",
            "Therapist slot open tomorrow 6 PM.",
            "No caregiver dependency blocker.",
        ],
        "policy_constraints": [
            "Confirm only when logistics are already clear.",
            "Do not escalate stable low-risk booking requests.",
        ],
        "allowed_actions": [
            "confirm_home_visit",
            "request_more_information",
            "schedule_callback",
            "close_with_guidance",
        ],
        "max_steps": 1,
        "success_score_threshold": 0.72,
        "truth": {
            "intent": "book_visit",
            "acceptable_intents": [],
            "component_intents": [],
            "risk_level": "low",
            "acceptable_risk_levels": ["medium"],
            "next_action": "confirm_home_visit",
            "acceptable_actions": [],
            "required_secondary_actions": [],
            "acceptable_secondary_actions": [],
            "logistics_valid_actions": ["confirm_home_visit"],
            "forbidden_actions": ["escalate_for_emergency_attention", "priority_callback"],
            "clarification_acceptable": False,
            "escalation_required": False,
            "risk_flag": "standard_booking_case",
            "summary_keyword_groups": [
                ["booking", "home physiotherapy", "new referral"],
                ["low", "stable"],
                ["confirm_home_visit", "confirmed", "booked"],
                ["tomorrow evening", "6 PM", "accessible"],
            ],
            "reply_keyword_groups": [
                ["home visit", "physiotherapy session"],
                ["confirmed", "booked", "scheduled"],
                ["tomorrow evening", "6 PM"],
            ],
        },
    },
    {
        "task_id": "reschedule_caregiver_access",
        "task_family": "rescheduling",
        "patient_message": (
            "Our caregiver will not be home for today's 4 PM physio visit and the building lift is out. "
            "Please move it to tomorrow afternoon."
        ),
        "patient_history_summary": "Stroke rehab follow-up. Needs assisted transfer support for safe home sessions.",
        "care_plan_summary": "Ongoing home physio, currently 3 sessions per week. Existing visit booked for today 4 PM.",
        "visit_context": {
            "location": "Powai",
            "preferred_window": "tomorrow afternoon",
            "scheduled_visit": "today 4 PM",
            "caregiver_required": True,
            "home_access": "stairs only until lift repair",
        },
        "appointment_context": {
            "existing_visit": "today 4 PM",
            "therapist_availability": "tomorrow 2 PM available",
            "serviceability_notes": "temporary access blocker",
        },
        "hidden_state": {
            "true_clinical_severity": "medium",
            "home_visit_suitability": "needs_review",
            "latent_adherence_risk": "medium",
            "escalation_necessity": "none",
            "serviceability_status": "restricted",
        },
        "operational_constraints": [
            "Visit requires caregiver present for transfers.",
            "Home access is temporarily difficult without lift.",
            "Tomorrow 2 PM slot is available.",
        ],
        "policy_constraints": [
            "Avoid confirming unsafe home visits when access or caregiver support is blocked.",
            "Reschedule when logistics blockers are temporary and clinically stable.",
        ],
        "allowed_actions": [
            "reschedule_home_visit",
            "modify_visit_plan",
            "request_more_information",
            "convert_to_remote_checkin",
        ],
        "max_steps": 1,
        "success_score_threshold": 0.72,
        "truth": {
            "intent": "reschedule_visit",
            "acceptable_intents": ["caregiver_unavailable", "home_access_issue", "mixed_intent"],
            "component_intents": ["caregiver_unavailable", "home_access_issue"],
            "risk_level": "medium",
            "acceptable_risk_levels": ["low"],
            "next_action": "reschedule_home_visit",
            "acceptable_actions": ["modify_visit_plan"],
            "required_secondary_actions": [],
            "acceptable_secondary_actions": [],
            "logistics_valid_actions": ["reschedule_home_visit", "modify_visit_plan", "convert_to_remote_checkin"],
            "forbidden_actions": ["confirm_home_visit", "escalate_for_emergency_attention"],
            "clarification_acceptable": False,
            "escalation_required": False,
            "risk_flag": "caregiver_access_blocker",
            "summary_keyword_groups": [
                ["reschedule", "move visit"],
                ["medium", "logistics"],
                ["caregiver", "lift", "stairs"],
                ["tomorrow afternoon", "2 PM"],
            ],
            "reply_keyword_groups": [
                ["reschedule", "move"],
                ["tomorrow afternoon", "2 PM"],
                ["caregiver", "access", "lift"],
            ],
        },
    },
    {
        "task_id": "callback_worsening_pain",
        "task_family": "callback",
        "patient_message": (
            "My lower back pain has been getting worse since yesterday after therapy. "
            "Can someone call me before tomorrow's home session?"
        ),
        "patient_history_summary": "Chronic lumbar pain. No fall reported. Pain increased from 4/10 to 7/10 overnight.",
        "care_plan_summary": "Home exercise reinforcement and mobility work. Next visit planned tomorrow 11 AM.",
        "visit_context": {
            "location": "Bandra",
            "preferred_window": "today before 7 PM",
            "scheduled_visit": "tomorrow 11 AM",
            "caregiver_required": False,
            "home_access": "accessible",
        },
        "appointment_context": {
            "existing_visit": "tomorrow 11 AM",
            "therapist_availability": "phone review available this evening",
            "serviceability_notes": "visit should be reviewed before proceeding",
        },
        "hidden_state": {
            "true_clinical_severity": "high",
            "home_visit_suitability": "needs_review",
            "latent_adherence_risk": "medium",
            "escalation_necessity": "callback",
            "serviceability_status": "serviceable",
        },
        "operational_constraints": [
            "Therapist is available for phone review this evening.",
            "In-person visit should not be confirmed unchanged until symptoms are reviewed.",
        ],
        "policy_constraints": [
            "Worsening pain before the next visit requires callback planning.",
            "Safety review comes before routine scheduling language.",
        ],
        "allowed_actions": [
            "schedule_callback",
            "priority_callback",
            "notify_therapist",
            "request_more_information",
            "modify_visit_plan",
        ],
        "max_steps": 1,
        "success_score_threshold": 0.72,
        "truth": {
            "intent": "request_callback",
            "acceptable_intents": ["report_worsening_pain", "mixed_intent"],
            "component_intents": ["request_callback", "report_worsening_pain"],
            "risk_level": "high",
            "acceptable_risk_levels": ["medium"],
            "next_action": "schedule_callback",
            "acceptable_actions": ["priority_callback"],
            "required_secondary_actions": ["notify_therapist"],
            "acceptable_secondary_actions": ["modify_visit_plan"],
            "logistics_valid_actions": ["schedule_callback", "priority_callback", "modify_visit_plan"],
            "forbidden_actions": ["confirm_home_visit", "close_with_guidance"],
            "clarification_acceptable": False,
            "escalation_required": True,
            "risk_flag": "worsening_pain_callback",
            "summary_keyword_groups": [
                ["worsening pain", "pain increased", "7/10"],
                ["high", "urgent callback"],
                ["schedule_callback", "priority_callback", "phone review"],
                ["tomorrow 11 AM", "before next visit"],
            ],
            "reply_keyword_groups": [
                ["sorry", "understand"],
                ["call", "callback", "review"],
                ["before tomorrow", "today", "this evening"],
            ],
        },
    },
    {
        "task_id": "priority_severe_pain_emergency",
        "task_family": "priority_pain",
        "patient_message": (
            "My father has severe chest tightness and extreme pain after the therapy session. "
            "He needs urgent help right now."
        ),
        "patient_history_summary": "Recent pulmonary rehab patient. Family reports sudden severe discomfort after today's session.",
        "care_plan_summary": "High-touch home rehab follow-up. No future visit should proceed without clinical clearance.",
        "visit_context": {
            "location": "Dadar",
            "preferred_window": "immediate",
            "scheduled_visit": "tomorrow 9 AM",
            "caregiver_required": True,
            "home_access": "accessible",
        },
        "appointment_context": {
            "existing_visit": "tomorrow 9 AM",
            "therapist_availability": "urgent review only after emergency handling",
            "serviceability_notes": "routine visit planning suspended",
        },
        "hidden_state": {
            "true_clinical_severity": "critical",
            "home_visit_suitability": "unsuitable",
            "latent_adherence_risk": "high",
            "escalation_necessity": "emergency",
            "serviceability_status": "blocked",
        },
        "operational_constraints": [
            "Current symptoms are outside routine scheduling workflow.",
            "Emergency escalation takes precedence over callback or booking changes.",
        ],
        "policy_constraints": [
            "Chest tightness with extreme pain must be treated as emergency attention.",
            "Do not offer routine visit confirmation in a critical safety case.",
        ],
        "allowed_actions": [
            "priority_callback",
            "notify_therapist",
            "escalate_for_clinical_review",
            "escalate_for_emergency_attention",
        ],
        "max_steps": 1,
        "success_score_threshold": 0.8,
        "truth": {
            "intent": "report_worsening_pain",
            "acceptable_intents": ["request_callback", "mixed_intent"],
            "component_intents": ["request_callback", "report_worsening_pain"],
            "risk_level": "critical",
            "acceptable_risk_levels": ["high"],
            "next_action": "escalate_for_emergency_attention",
            "acceptable_actions": ["priority_callback"],
            "required_secondary_actions": ["notify_therapist"],
            "acceptable_secondary_actions": ["escalate_for_clinical_review"],
            "logistics_valid_actions": ["escalate_for_emergency_attention", "priority_callback"],
            "forbidden_actions": ["confirm_home_visit", "reschedule_home_visit", "close_with_guidance"],
            "clarification_acceptable": False,
            "escalation_required": True,
            "risk_flag": "critical_pain_case",
            "summary_keyword_groups": [
                ["chest tightness", "extreme pain", "urgent help"],
                ["critical", "emergency"],
                ["escalate_for_emergency_attention", "emergency attention", "urgent escalation"],
                ["therapist", "clinical clearance"],
            ],
            "reply_keyword_groups": [
                ["urgent", "immediately", "emergency"],
                ["call emergency", "seek emergency care", "emergency attention"],
                ["team", "therapist", "contact"],
            ],
        },
    },
    {
        "task_id": "mixed_intent_priority_reschedule",
        "task_family": "priority_pain",
        "patient_message": (
            "Pain shot up to 8 out of 10 overnight, and I cannot manage the stairs today. "
            "Please move tomorrow's home visit and have someone call me first."
        ),
        "patient_history_summary": "Hip rehab patient with prior adherence concerns. Pain flare and mobility difficulty reported.",
        "care_plan_summary": "Home strengthening plan. Next visit scheduled tomorrow 10 AM.",
        "visit_context": {
            "location": "Chembur",
            "preferred_window": "today for callback, tomorrow only if plan is adjusted",
            "scheduled_visit": "tomorrow 10 AM",
            "caregiver_required": False,
            "home_access": "stairs only",
        },
        "appointment_context": {
            "existing_visit": "tomorrow 10 AM",
            "therapist_availability": "callback today, visit review pending",
            "serviceability_notes": "stairs-only access raises safety concerns",
        },
        "hidden_state": {
            "true_clinical_severity": "high",
            "home_visit_suitability": "needs_review",
            "latent_adherence_risk": "high",
            "escalation_necessity": "priority_callback",
            "serviceability_status": "restricted",
        },
        "operational_constraints": [
            "Current stairs-only access may make the next home visit unsuitable.",
            "Pain spike needs review before confirming any reschedule.",
        ],
        "policy_constraints": [
            "When safety and scheduling are mixed, safety intervention comes first.",
            "Do not simply reschedule without callback planning for pain flare.",
        ],
        "allowed_actions": [
            "priority_callback",
            "reschedule_home_visit",
            "modify_visit_plan",
            "notify_therapist",
            "escalate_for_clinical_review",
            "request_more_information",
        ],
        "max_steps": 1,
        "success_score_threshold": 0.76,
        "truth": {
            "intent": "mixed_intent",
            "acceptable_intents": ["request_callback", "report_worsening_pain", "home_access_issue"],
            "component_intents": ["request_callback", "report_worsening_pain", "home_access_issue", "reschedule_visit"],
            "risk_level": "high",
            "acceptable_risk_levels": ["critical"],
            "next_action": "priority_callback",
            "acceptable_actions": ["escalate_for_clinical_review"],
            "required_secondary_actions": ["notify_therapist", "modify_visit_plan"],
            "acceptable_secondary_actions": ["reschedule_home_visit"],
            "logistics_valid_actions": ["priority_callback", "modify_visit_plan", "escalate_for_clinical_review"],
            "forbidden_actions": ["confirm_home_visit", "close_with_guidance"],
            "clarification_acceptable": False,
            "escalation_required": True,
            "risk_flag": "priority_pain_case",
            "summary_keyword_groups": [
                ["pain shot up", "8 out of 10", "pain flare"],
                ["high", "priority"],
                ["priority_callback", "call first"],
                ["stairs", "modify_visit_plan", "tomorrow 10 AM"],
            ],
            "reply_keyword_groups": [
                ["sorry", "understand"],
                ["priority callback", "call you quickly", "call first"],
                ["review", "adjust the visit plan", "before tomorrow"],
            ],
        },
    },
]

TASKS_BY_ID = {task["task_id"]: task for task in TASKS}
